services:
  vgt-api: 
    container_name: vgt-api
    image: vgt-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 2138:80
    environment:
      - HOTEL_API=172.17.0.1:3002
      - FLIGHT_API=172.17.0.1:3001
      - BROKER=172.17.0.1:5672
    networks:
      - vgt-network
networks:
  vgt-network:
    name: vgt-network
    external: true
